apiVersion: v1
kind: ConfigMap
metadata:
  name: region-config
  namespace: production
data:
  region-name: "eu-west-1"
  region-display-name: "EU West (Ireland)"
  primary-region: "false"
  data-residency-zone: "eu"
  api-endpoint: "api-eu.hedgefund-trading.com"
  websocket-endpoint: "ws-eu.hedgefund-trading.com"
  cdn-endpoint: "cdn-eu.hedgefund-trading.com"
  backup-regions: "us-east-1,ap-southeast-1"
  market-data-sources: "lse,euronext,xetra"
  regulatory-jurisdiction: "eu-gdpr,eu-mifid"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hftp-config
  namespace: production
data:
  redis-host: "redis-master.eu-west-1.hedgefund-trading.internal"
  redis-port: "6379"
  postgres-host: "postgres-master.eu-west-1.hedgefund-trading.internal"
  postgres-port: "5432"
  timescale-host: "timescale-master.eu-west-1.hedgefund-trading.internal"
  timescale-port: "5432"
  kafka-brokers: "kafka-0.eu-west-1.hedgefund-trading.internal:9092,kafka-1.eu-west-1.hedgefund-trading.internal:9092,kafka-2.eu-west-1.hedgefund-trading.internal:9092"
  elasticsearch-endpoint: "elasticsearch.eu-west-1.hedgefund-trading.internal:9200"
  log-level: "info"
  feature-flags: '{"enhancedAnalytics":true,"advancedRiskModels":true,"aiTradingSignals":true}'
  max-connections: "1000"
  connection-timeout: "30"
  region-specific-settings: '{"dataRetentionDays":365,"maxHistoricalDataPoints":10000,"defaultCurrency":"EUR","gdprCompliance":true,"dataMinimization":true}'