FROM node:16-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY hedge-fund-app/package*.json ./

# Install dependencies with legacy-peer-deps flag
RUN npm install --legacy-peer-deps

# Copy project files
COPY hedge-fund-app/ .

# Expose the port the app runs on
EXPOSE 3000

# Command to run the application in development mode
CMD ["npm", "start"]