FROM node:16-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY hedge-fund-app/package*.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY hedge-fund-app/ .

# Build the app
RUN npm run build

# Install serve to run the application
RUN npm install -g serve

# Expose the port the app runs on
EXPOSE 3000

# Command to run the application in development mode
CMD ["npm", "start"]